//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.User {
    
    public partial class ForgotPassword {
        
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        
        protected global::System.Web.UI.WebControls.Button btnSend;
        
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}



