//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.User
{


    public partial class LinkChecker
    {
        /// <summary>
        /// txtUrlInput control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUrlInput;

        /// <summary>
        /// btnCheckLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCheckLink;

        /// <summary>
        /// lblResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResult;
    }
}
