//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.User
{
    public partial class ModuleInformation
    {
        protected global::System.Web.UI.WebControls.Panel pnlContent;
        protected global::System.Web.UI.WebControls.Panel pnlUnavailable;
        protected global::System.Web.UI.WebControls.HyperLink lnkBackToEdit;
        protected global::System.Web.UI.WebControls.Label lblModuleName;
        protected global::System.Web.UI.WebControls.Label lblIntroduction;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblAuthor;
        protected global::System.Web.UI.WebControls.Label lblDate;
        protected global::System.Web.UI.WebControls.Label lblHeader1;
        protected global::System.Web.UI.WebControls.Label lblHeader1Text;
        protected global::System.Web.UI.WebControls.Label lblHeader2;
        protected global::System.Web.UI.WebControls.Label lblHeader2Text;
        protected global::System.Web.UI.WebControls.Label lblHeader3;
        protected global::System.Web.UI.WebControls.Label lblHeader3Text;
        protected global::System.Web.UI.WebControls.Label lblHeader4;
        protected global::System.Web.UI.WebControls.Label lblHeader4Text;
        protected global::System.Web.UI.WebControls.Label lblHeader5;
        protected global::System.Web.UI.WebControls.Label lblHeader5Text;
        protected global::System.Web.UI.WebControls.Image img1;
        protected global::System.Web.UI.WebControls.Image img2;
        protected global::System.Web.UI.WebControls.Label lblCompleteMessage;
        protected global::System.Web.UI.WebControls.Button btnCompleteModule;
        protected global::System.Web.UI.WebControls.HyperLink lnkTakeQuiz;
        protected global::System.Web.UI.WebControls.HyperLink lnkBackToModules;
    }
}
