//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.User {
    
    public partial class ResetPassword {
        
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.PlaceHolder phForm;
        
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        
        protected global::System.Web.UI.WebControls.TextBox txtConfirm;
        
        protected global::System.Web.UI.WebControls.Button btnReset;
        
        protected global::System.Web.UI.WebControls.PlaceHolder phBackOnly;
    }
}



