//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.User {
    
    public partial class VerifyEmail {
        
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        
        protected global::System.Web.UI.WebControls.TextBox txtCode;
        
        protected global::System.Web.UI.WebControls.Button btnVerify;
        
        protected global::System.Web.UI.WebControls.Button btnResend;
        
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}


