//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.Staff
{

	public partial class ManageStaff
	{
		protected global::System.Web.UI.WebControls.Label lblMessage;
		protected global::System.Web.UI.WebControls.GridView gvStaff;
		protected global::System.Web.UI.WebControls.TextBox txtSearch;
		protected global::System.Web.UI.WebControls.Button btnFilter;
		protected global::System.Web.UI.WebControls.Button btnClearFilters;
	}
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.Staff
{


    public partial class ManageStaff
    {
    }
}
