//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.Staff
{


    public partial class StaffDashboard
    {

        /// <summary>
        /// phDashboard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phDashboard;

        /// <summary>
        /// lblStaffName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblStaffName;

        /// <summary>
        /// phPleaseLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phPleaseLogin;

        /// <summary>
        /// ddlRange control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRange;

        /// <summary>
        /// btnApply control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApply;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// gvTopTypes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTopTypes;

        /// <summary>
        /// gvTopChannels control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTopChannels;

        /// <summary>
        /// gvGaps control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvGaps;

        /// <summary>
        /// lblGapsHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblGapsHint;
    }
}
