//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.Staff
{


<<<<<<<< HEAD:SpotTheScam/Staff/StaffLogout.aspx.designer.cs
    public partial class StaffLogout
========
    public partial class WebForm1
>>>>>>>> 16d5c3224740bd90b5e14147468f61e05bb20cc5:SpotTheScam/WebForm1.aspx.designer.cs
    {
    }
}
