//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotTheScam.Staff {
    
    public partial class TrendAnalytics {
        
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlRange;
        
        protected global::System.Web.UI.WebControls.Button btnApply;
        
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.GridView gvTopTypes;
        
        protected global::System.Web.UI.WebControls.GridView gvTopChannels;
        
        protected global::System.Web.UI.WebControls.GridView gvGaps;
        
        protected global::System.Web.UI.WebControls.Label lblGapsHint;
    }
}


